version: '2'

services:
  web :
    build : 
      context : "."
      dockerfile: Dockerfile.prod
    expose:
      - 8000
    env_file:
      - .env.prod
    volumes:
      - static_volume:/src/staticfiles
      - media_volume:/src/media
    # command: python manage.py runserver 0.0.0.0:8000
    command: gunicorn ruptures_interface.wsgi:application --bind 0.0.0.0:8000
  
  nginx:
    build: ./nginx
    ports:
      - 1337:80
    volumes:
      - static_volume:/src/staticfiles
      - media_volume:/src/media
    depends_on:
      - web
volumes:
  static_volume:
  media_volume: