FROM python:3.9-bullseye

ENV PYTHONUNBUFFERED 1

# create directory for the app user
RUN mkdir -p /home/app


WORKDIR /src

ADD requirements.txt /src

RUN pip install --upgrade pip && pip install -r requirements.txt

ADD . /src/
